//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AaltoWindraw.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AaltoWindraw.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aaltowindraw.
        /// </summary>
        public static string application_protocol_name {
            get {
                return ResourceManager.GetString("application_protocol_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYEBYE.
        /// </summary>
        public static string bye_message {
            get {
                return ResourceManager.GetString("bye_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to otaniemi.
        /// </summary>
        public static string client_name {
            get {
                return ResourceManager.GetString("client_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12319.
        /// </summary>
        public static string default_port {
            get {
                return ResourceManager.GetString("default_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .draw.
        /// </summary>
        public static string drawing_file_extension {
            get {
                return ResourceManager.GetString("drawing_file_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_{1}_{2:00}{3:00}{4:00}{5:00}{6:00}{7:00}.
        /// </summary>
        public static string drawing_file_format {
            get {
                return ResourceManager.GetString("drawing_file_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100.
        /// </summary>
        public static string maximum_connections {
            get {
                return ResourceManager.GetString("maximum_connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1.
        /// </summary>
        public static string server_address {
            get {
                return ResourceManager.GetString("server_address", resourceCulture);
            }
        }
    }
}
